// <auto-generated>
// Automatically generated by the tool, do not modify
// </auto-generated>

using System.Diagnostics;
using UIFramework.Runtime;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

namespace SurvivorX.UI.GameRunning
{
    public class GameRunningUI : BaseUI
    {
        public RectTransform TmpExpTrans;
        public TextMeshProUGUI TmpExpTmp;
        public GameObject TmpExpGo;

        [Conditional("UNITY_EDITOR")]
        private void BindComponent()
        {
            Canvas = GetComponent<Canvas>();
            Raycaster = GetComponent<GraphicRaycaster>();
            Content = transform.Find("Content") as RectTransform;
            BlackImage = GetComponent<Image>();
            Raycast = transform.Find("Raycast").GetComponent<UIRaycast>();
        
            var TmpExp = transform.Find("Content/TmpExp");
        
            TmpExpTrans = TmpExp.GetComponent<RectTransform>();
            TmpExpTmp = TmpExp.GetComponent<TextMeshProUGUI>();
            TmpExpGo = TmpExp.gameObject;
        }
    }
}